// Error code constants

export const ERROR_CODES = {
  // Generic errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CONFLICT: 'CONFLICT',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_LENGTH: 'INVALID_LENGTH',
  INVALID_RANGE: 'INVALID_RANGE',
  INVALID_TYPE: 'INVALID_TYPE',
  MISSING_REQUIRED: 'MISSING_REQUIRED',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',

  // Authentication & Authorization errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  PASSWORD_EXPIRED: 'PASSWORD_EXPIRED',

  // User management errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_UNVERIFIED: 'USER_UNVERIFIED',
  INVALID_USER_STATUS: 'INVALID_USER_STATUS',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  SETTINGS_NOT_FOUND: 'SETTINGS_NOT_FOUND',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_PHONE: 'INVALID_PHONE',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',

  // Payment errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_PARTIALLY_REFUNDED: 'PAYMENT_PARTIALLY_REFUNDED',
  PAYMENT_CHARGEBACK: 'PAYMENT_CHARGEBACK',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_INVALID: 'INVOICE_INVALID',
  INVOICE_OVERDUE: 'INVOICE_OVERDUE',
  PAYMENT_METHOD_INVALID: 'PAYMENT_METHOD_INVALID',
  PAYMENT_METHOD_EXPIRED: 'PAYMENT_METHOD_EXPIRED',
  PAYMENT_METHOD_NOT_FOUND: 'PAYMENT_METHOD_NOT_FOUND',
  DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',
  PAYMENT_LIMIT_EXCEEDED: 'PAYMENT_LIMIT_EXCEEDED',
  CURRENCY_NOT_SUPPORTED: 'CURRENCY_NOT_SUPPORTED',
  MERCHANT_ACCOUNT_INVALID: 'MERCHANT_ACCOUNT_INVALID',

  // Order errors
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID: 'ORDER_INVALID',
  ORDER_ALREADY_PROCESSED: 'ORDER_ALREADY_PROCESSED',
  ORDER_CANNOT_BE_CANCELLED: 'ORDER_CANNOT_BE_CANCELLED',
  ORDER_CANNOT_BE_SHIPPED: 'ORDER_CANNOT_BE_SHIPPED',
  ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  SHIPPING_ADDRESS_INVALID: 'SHIPPING_ADDRESS_INVALID',
  BILLING_ADDRESS_INVALID: 'BILLING_ADDRESS_INVALID',
  ORDER_VALUE_INVALID: 'ORDER_VALUE_INVALID',
  ORDER_QUANTITY_INVALID: 'ORDER_QUANTITY_INVALID',
  SHIPPING_METHOD_INVALID: 'SHIPPING_METHOD_INVALID',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  ORDER_EXPIRED: 'ORDER_EXPIRED',

  // Subscription errors
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_EXISTS: 'SUBSCRIPTION_ALREADY_EXISTS',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_SUSPENDED: 'SUBSCRIPTION_SUSPENDED',
  SUBSCRIPTION_PLAN_NOT_FOUND: 'SUBSCRIPTION_PLAN_NOT_FOUND',
  SUBSCRIPTION_PLAN_INVALID: 'SUBSCRIPTION_PLAN_INVALID',
  SUBSCRIPTION_LIMIT_EXCEEDED: 'SUBSCRIPTION_LIMIT_EXCEEDED',
  USAGE_LIMIT_EXCEEDED: 'USAGE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  TRIAL_EXPIRED: 'TRIAL_EXPIRED',
  TRIAL_NOT_AVAILABLE: 'TRIAL_NOT_AVAILABLE',
  BILLING_CYCLE_INVALID: 'BILLING_CYCLE_INVALID',
  SUBSCRIPTION_CHANGE_NOT_ALLOWED: 'SUBSCRIPTION_CHANGE_NOT_ALLOWED',
  GRACE_PERIOD_EXPIRED: 'GRACE_PERIOD_EXPIRED',

  // Notification errors
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  NOTIFICATION_ALREADY_SENT: 'NOTIFICATION_ALREADY_SENT',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_INVALID: 'TEMPLATE_INVALID',
  TEMPLATE_RENDER_FAILED: 'TEMPLATE_RENDER_FAILED',
  RECIPIENT_INVALID: 'RECIPIENT_INVALID',
  RECIPIENT_NOT_FOUND: 'RECIPIENT_NOT_FOUND',
  CHANNEL_NOT_SUPPORTED: 'CHANNEL_NOT_SUPPORTED',
  SENDER_INVALID: 'SENDER_INVALID',
  NOTIFICATION_RATE_LIMITED: 'NOTIFICATION_RATE_LIMITED',
  EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',
  SMS_DELIVERY_FAILED: 'SMS_DELIVERY_FAILED',
  PUSH_NOTIFICATION_FAILED: 'PUSH_NOTIFICATION_FAILED',
  NOTIFICATION_PREFERENCES_INVALID: 'NOTIFICATION_PREFERENCES_INVALID',

  // File and storage errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',
  CORRUPTED_FILE: 'CORRUPTED_FILE',
  FILE_PROCESSING_FAILED: 'FILE_PROCESSING_FAILED',
  STORAGE_SERVICE_UNAVAILABLE: 'STORAGE_SERVICE_UNAVAILABLE',
  INSUFFICIENT_STORAGE: 'INSUFFICIENT_STORAGE',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',

  // Database errors
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  DATABASE_QUERY_FAILED: 'DATABASE_QUERY_FAILED',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
  DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_DUPLICATE_ENTRY: 'DATABASE_DUPLICATE_ENTRY',
  DATABASE_FOREIGN_KEY_VIOLATION: 'DATABASE_FOREIGN_KEY_VIOLATION',
  DATABASE_TRANSACTION_FAILED: 'DATABASE_TRANSACTION_FAILED',
  DATABASE_MIGRATION_FAILED: 'DATABASE_MIGRATION_FAILED',
  DATABASE_BACKUP_FAILED: 'DATABASE_BACKUP_FAILED',
  DATABASE_RESTORE_FAILED: 'DATABASE_RESTORE_FAILED',
  DATABASE_CONNECTION_POOL_EXHAUSTED: 'DATABASE_CONNECTION_POOL_EXHAUSTED',

  // External service errors
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_RATE_LIMITED: 'EXTERNAL_SERVICE_RATE_LIMITED',
  EXTERNAL_SERVICE_AUTHENTICATION_FAILED: 'EXTERNAL_SERVICE_AUTHENTICATION_FAILED',
  EXTERNAL_SERVICE_INVALID_RESPONSE: 'EXTERNAL_SERVICE_INVALID_RESPONSE',
  EXTERNAL_SERVICE_CONFIGURATION_ERROR: 'EXTERNAL_SERVICE_CONFIGURATION_ERROR',
  EXTERNAL_SERVICE_QUOTA_EXCEEDED: 'EXTERNAL_SERVICE_QUOTA_EXCEEDED',
  EXTERNAL_SERVICE_API_VERSION_UNSUPPORTED: 'EXTERNAL_SERVICE_API_VERSION_UNSUPPORTED',
  EXTERNAL_SERVICE_MAINTENANCE: 'EXTERNAL_SERVICE_MAINTENANCE',

  // Rate limiting and quota errors
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  QUOTA_LIMIT_EXCEEDED: 'QUOTA_LIMIT_EXCEEDED',
  API_LIMIT_EXCEEDED: 'API_LIMIT_EXCEEDED',
  CONCURRENT_LIMIT_EXCEEDED: 'CONCURRENT_LIMIT_EXCEEDED',
  BANDWIDTH_LIMIT_EXCEEDED: 'BANDWIDTH_LIMIT_EXCEEDED',
  REQUEST_SIZE_LIMIT_EXCEEDED: 'REQUEST_SIZE_LIMIT_EXCEEDED',
  RESPONSE_SIZE_LIMIT_EXCEEDED: 'RESPONSE_SIZE_LIMIT_EXCEEDED',

  // Configuration errors
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  MISSING_CONFIGURATION: 'MISSING_CONFIGURATION',
  ENVIRONMENT_VARIABLE_MISSING: 'ENVIRONMENT_VARIABLE_MISSING',
  FEATURE_FLAG_DISABLED: 'FEATURE_FLAG_DISABLED',
  SERVICE_CONFIGURATION_INVALID: 'SERVICE_CONFIGURATION_INVALID',

  // Audit and logging errors
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',
  AUDIT_ENTRY_NOT_FOUND: 'AUDIT_ENTRY_NOT_FOUND',
  AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',
  LOG_WRITE_FAILED: 'LOG_WRITE_FAILED',
  LOG_ROTATION_FAILED: 'LOG_ROTATION_FAILED',
  LOG_PARSING_FAILED: 'LOG_PARSING_FAILED',
  AUDIT_RETENTION_POLICY_VIOLATION: 'AUDIT_RETENTION_POLICY_VIOLATION',

  // Network and connectivity errors
  NETWORK_UNAVAILABLE: 'NETWORK_UNAVAILABLE',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  CONNECTION_RESET: 'CONNECTION_RESET',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
  DNS_RESOLUTION_FAILED: 'DNS_RESOLUTION_FAILED',
  SSL_CERTIFICATE_ERROR: 'SSL_CERTIFICATE_ERROR',
  PROXY_ERROR: 'PROXY_ERROR',
  FIREWALL_BLOCKED: 'FIREWALL_BLOCKED',

  // Security errors
  SECURITY_VIOLATION: 'SECURITY_VIOLATION',
  ACCESS_DENIED: 'ACCESS_DENIED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
  TOKEN_BLACKLISTED: 'TOKEN_BLACKLISTED',
  SESSION_HIJACKED: 'SESSION_HIJACKED',
  BRUTE_FORCE_DETECTED: 'BRUTE_FORCE_DETECTED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  MALICIOUS_REQUEST: 'MALICIOUS_REQUEST',
  REQUEST_FORGED: 'REQUEST_FORGED',
  CORS_VIOLATION: 'CORS_VIOLATION',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',

  // Business logic errors
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  RESOURCE_NOT_AVAILABLE: 'RESOURCE_NOT_AVAILABLE',
  RESOURCE_ALREADY_ALLOCATED: 'RESOURCE_ALREADY_ALLOCATED',
  CONDITION_NOT_MET: 'CONDITION_NOT_MET',
  DEPENDENCY_MISSING: 'DEPENDENCY_MISSING',
  WORKFLOW_ERROR: 'WORKFLOW_ERROR',
  STATE_TRANSITION_INVALID: 'STATE_TRANSITION_INVALID',
  CONFLICTING_OPERATION: 'CONFLICTING_OPERATION',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  VERSION_CONFLICT: 'VERSION_CONFLICT',

  // Data integrity errors
  DATA_CORRUPTION: 'DATA_CORRUPTION',
  DATA_INCONSISTENCY: 'DATA_INCONSISTENCY',
  REFERENTIAL_INTEGRITY_VIOLATION: 'REFERENTIAL_INTEGRITY_VIOLATION',
  UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_CONSTRAINT_VIOLATION: 'FOREIGN_KEY_CONSTRAINT_VIOLATION',
  CHECK_CONSTRAINT_VIOLATION: 'CHECK_CONSTRAINT_VIOLATION',
  NOT_NULL_VIOLATION: 'NOT_NULL_VIOLATION',
  DOMAIN_VIOLATION: 'DOMAIN_VIOLATION',

  // System errors
  SYSTEM_OVERLOAD: 'SYSTEM_OVERLOAD',
  MEMORY_EXHAUSTED: 'MEMORY_EXHAUSTED',
  DISK_FULL: 'DISK_FULL',
  CPU_OVERLOAD: 'CPU_OVERLOAD',
  THREAD_POOL_EXHAUSTED: 'THREAD_POOL_EXHAUSTED',
  FILE_SYSTEM_ERROR: 'FILE_SYSTEM_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RESOURCE_BUSY: 'RESOURCE_BUSY',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  DEADLOCK_DETECTED: 'DEADLOCK_DETECTED',

  // Feature-specific errors
  FEATURE_NOT_ENABLED: 'FEATURE_NOT_ENABLED',
  FEATURE_DEPRECATED: 'FEATURE_DEPRECATED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  BETA_FEATURE_ACCESS_DENIED: 'BETA_FEATURE_ACCESS_DENIED',
  PREMIUM_FEATURE_REQUIRED: 'PREMIUM_FEATURE_REQUIRED',

  // OAuth and authentication provider errors
  OAUTH_ERROR: 'OAUTH_ERROR',
  OAUTH_INVALID_CLIENT: 'OAUTH_INVALID_CLIENT',
  OAUTH_INVALID_GRANT: 'OAUTH_INVALID_GRANT',
  OAUTH_INVALID_SCOPE: 'OAUTH_INVALID_SCOPE',
  OAUTH_INVALID_REQUEST: 'OAUTH_INVALID_REQUEST',
  OAUTH_INVALID_TOKEN: 'OAUTH_INVALID_TOKEN',
  OAUTH_UNAUTHORIZED_CLIENT: 'OAUTH_UNAUTHORIZED_CLIENT',
  OAUTH_UNSUPPORTED_GRANT_TYPE: 'OAUTH_UNSUPPORTED_GRANT_TYPE',
  OAUTH_UNSUPPORTED_RESPONSE_TYPE: 'OAUTH_UNSUPPORTED_RESPONSE_TYPE',
  PROVIDER_CONNECTION_FAILED: 'PROVIDER_CONNECTION_FAILED',
  PROVIDER_API_ERROR: 'PROVIDER_API_ERROR',
} as const

// Error severity levels
export const ERROR_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const

// Error categories
export const ERROR_CATEGORIES = {
  CLIENT_ERROR: 'client_error',
  SERVER_ERROR: 'server_error',
  NETWORK_ERROR: 'network_error',
  DATABASE_ERROR: 'database_error',
  EXTERNAL_SERVICE_ERROR: 'external_service_error',
  BUSINESS_ERROR: 'business_error',
  SECURITY_ERROR: 'security_error',
  SYSTEM_ERROR: 'system_error',
} as const

// Error recovery strategies
export const ERROR_RECOVERY_STRATEGIES = {
  RETRY: 'retry',
  FALLBACK: 'fallback',
  DEGRADE: 'degrade',
  IGNORE: 'ignore',
  ALERT: 'alert',
  MANUAL_INTERVENTION: 'manual_intervention',
} as const

// Error monitoring tags
export const ERROR_TAGS = {
  USER_FACING: 'user_facing',
  INTERNAL: 'internal',
  CRITICAL: 'critical',
  SECURITY: 'security',
  PERFORMANCE: 'performance',
  AVAILABILITY: 'availability',
  DATA_INTEGRITY: 'data_integrity',
  COMPLIANCE: 'compliance',
} as const

// Utility functions
export const ErrorUtils = {
  // Check if error code is client error
  isClientError(errorCode: string): boolean {
    const clientErrorPatterns = [
      /^VALIDATION_/,
      /^INVALID_/,
      /^MISSING_/,
      /^UNAUTHORIZED/,
      /^FORBIDDEN/,
      /^NOT_FOUND/,
      /^CONFLICT/,
      /^RATE_LIMIT/,
      /^QUOTA_LIMIT/,
    ]
    return clientErrorPatterns.some(pattern => pattern.test(errorCode))
  },

  // Check if error code is server error
  isServerError(errorCode: string): boolean {
    const serverErrorPatterns = [
      /^INTERNAL_/,
      /^UNKNOWN_/,
      /^NOT_IMPLEMENTED/,
      /^SERVICE_/,
      /^DATABASE_/,
      /^SYSTEM_/,
      /^NETWORK_/,
    ]
    return serverErrorPatterns.some(pattern => pattern.test(errorCode))
  },

  // Check if error code is security related
  isSecurityError(errorCode: string): boolean {
    const securityErrorPatterns = [
      /^SECURITY_/,
      /^AUTHENTICATION_/,
      /^AUTHORIZATION_/,
      /^TOKEN_/,
      /^SESSION_/,
      /^BRUTE_FORCE/,
      /^SUSPICIOUS_/,
      /^MALICIOUS_/,
      /^FORGED/,
      /^CSRF_/,
      /^CORS_/,
    ]
    return securityErrorPatterns.some(pattern => pattern.test(errorCode))
  },

  // Check if error code is retryable
  isRetryableError(errorCode: string): boolean {
    const retryableErrors = [
      ERROR_CODES.SERVICE_UNAVAILABLE,
      ERROR_CODES.EXTERNAL_SERVICE_TIMEOUT,
      ERROR_CODES.EXTERNAL_SERVICE_UNAVAILABLE,
      ERROR_CODES.DATABASE_TIMEOUT,
      ERROR_CODES.NETWORK_TIMEOUT,
      ERROR_CODES.CONNECTION_FAILED,
      ERROR_CODES.SYSTEM_OVERLOAD,
    ]
    return retryableErrors.includes(errorCode as any)
  },

  // Check if error code should alert
  shouldAlert(errorCode: string): boolean {
    const alertingErrors = [
      ERROR_CODES.INTERNAL_ERROR,
      ERROR_CODES.SERVICE_UNAVAILABLE,
      ERROR_CODES.DATABASE_CONNECTION_FAILED,
      ERROR_CODES.SECURITY_VIOLATION,
      ERROR_CODES.DATA_CORRUPTION,
      ERROR_CODES.SYSTEM_OVERLOAD,
    ]
    return alertingErrors.includes(errorCode as any) || this.isSecurityError(errorCode)
  },

  // Get error category
  getErrorCategory(errorCode: string): keyof typeof ERROR_CATEGORIES {
    if (this.isClientError(errorCode)) return 'CLIENT_ERROR'
    if (this.isSecurityError(errorCode)) return 'SECURITY_ERROR'
    if (errorCode.startsWith('DATABASE_')) return 'DATABASE_ERROR'
    if (errorCode.startsWith('EXTERNAL_SERVICE_')) return 'EXTERNAL_SERVICE_ERROR'
    if (errorCode.startsWith('SYSTEM_') || errorCode.startsWith('NETWORK_')) return 'SYSTEM_ERROR'
    if (errorCode.startsWith('BUSINESS_')) return 'BUSINESS_ERROR'
    return 'SERVER_ERROR'
  },

  // Get HTTP status code for error
  getHttpStatus(errorCode: string): number {
    const statusMap: Record<string, number> = {
      [ERROR_CODES.VALIDATION_ERROR]: 400,
      [ERROR_CODES.INVALID_INPUT]: 400,
      [ERROR_CODES.INVALID_CREDENTIALS]: 401,
      [ERROR_CODES.TOKEN_EXPIRED]: 401,
      [ERROR_CODES.TOKEN_INVALID]: 401,
      [ERROR_CODES.UNAUTHORIZED]: 401,
      [ERROR_CODES.FORBIDDEN]: 403,
      [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
      [ERROR_CODES.USER_NOT_FOUND]: 404,
      [ERROR_CODES.ORDER_NOT_FOUND]: 404,
      [ERROR_CODES.PAYMENT_METHOD_NOT_FOUND]: 404,
      [ERROR_CODES.SUBSCRIPTION_NOT_FOUND]: 404,
      [ERROR_CODES.NOTIFICATION_NOT_FOUND]: 404,
      [ERROR_CODES.FILE_NOT_FOUND]: 404,
      [ERROR_CODES.CONFLICT]: 409,
      [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
      [ERROR_CODES.DUPLICATE_PAYMENT]: 409,
      [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
      [ERROR_CODES.QUOTA_LIMIT_EXCEEDED]: 429,
      [ERROR_CODES.INTERNAL_ERROR]: 500,
      [ERROR_CODES.UNKNOWN_ERROR]: 500,
      [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
    }
    return statusMap[errorCode] || 500
  },

  // Get user-friendly message
  getUserMessage(errorCode: string, defaultMessage: string = 'An error occurred'): string {
    const messages: Record<string, string> = {
      [ERROR_CODES.VALIDATION_ERROR]: 'Please check your input and try again',
      [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
      [ERROR_CODES.TOKEN_EXPIRED]: 'Your session has expired. Please log in again',
      [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Too many requests. Please try again later',
      [ERROR_CODES.PAYMENT_FAILED]: 'Your payment could not be processed. Please try again',
      [ERROR_CODES.FILE_TOO_LARGE]: 'The file is too large. Please choose a smaller file',
      [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service is temporarily unavailable. Please try again later',
    }
    return messages[errorCode] || defaultMessage
  },

  // Check if error should be logged
  shouldLog(errorCode: string, severity: keyof typeof ERROR_SEVERITY): boolean {
    const criticalErrors = [
      ERROR_CODES.INTERNAL_ERROR,
      ERROR_CODES.SERVICE_UNAVAILABLE,
      ERROR_CODES.SECURITY_VIOLATION,
      ERROR_CODES.DATA_CORRUPTION,
    ]

    return criticalErrors.includes(errorCode as any) ||
           severity === ERROR_SEVERITY.HIGH ||
           severity === ERROR_SEVERITY.CRITICAL
  },

  // Get error recovery strategy
  getRecoveryStrategy(errorCode: string): keyof typeof ERROR_RECOVERY_STRATEGIES {
    const retryableErrors = [
      ERROR_CODES.SERVICE_UNAVAILABLE,
      ERROR_CODES.EXTERNAL_SERVICE_TIMEOUT,
      ERROR_CODES.NETWORK_TIMEOUT,
    ]

    const fallbackErrors = [
      ERROR_CODES.EXTERNAL_SERVICE_UNAVAILABLE,
      ERROR_CODES.STORAGE_SERVICE_UNAVAILABLE,
    ]

    const degradeErrors = [
      ERROR_CODES.SYSTEM_OVERLOAD,
      ERROR_CODES.DATABASE_TIMEOUT,
    ]

    if (retryableErrors.includes(errorCode as any)) return 'RETRY'
    if (fallbackErrors.includes(errorCode as any)) return 'FALLBACK'
    if (degradeErrors.includes(errorCode as any)) return 'DEGRADE'

    return 'ALERT'
  },
}

export default {
  ERROR_CODES,
  ERROR_SEVERITY,
  ERROR_CATEGORIES,
  ERROR_RECOVERY_STRATEGIES,
  ERROR_TAGS,
  ErrorUtils,
}
